### ISSUE TITLE
Make it possible to turn off the println! statements

### ISSUE THREAD

**Issue by philbooth** [taskcluster/rust-hawk#12]
There's some `println!` invocations in this crate that show up in our logs. Ideally we want our all our log lines to be mozlog-parseable so they're kind of annoying in that sense. And they mess up the output from `cargo test` a bit too.

Would you be open to a PR that made them turn-offable? Or, if they're just a hangover from old debugging stuff that's no longer needed, a PR that removed them? I'm happy to do either if you're ok with it.

**Comment by djmitche** [comment]
Indeed, I'll remove them.  I often miss removing those since, once the test suite is passing, they don't show up anymore.
