### ISSUE TITLE
Make a 0.3.1 release

### ISSUE THREAD

**Issue by eoger** [taskcluster/rust-hawk#53]
Having 97358aa1a84b5259b3dca21720e1455f6169df00 released would help me not introduce another copy of `base64` in mozilla-central.

**Comment by eoger** [comment]
cc @djmitche  :)

**Comment by djmitche** [comment]
That'll be 3.1.1, not 0.3.1 :)

**Comment by djmitche** [comment]
done!

**Comment by eoger** [comment]
> That'll be 3.1.1, not 0.3.1 :)

Ha indeed :) Thank you so much!
