### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/rust-hawk#65]
I was looking at duplicates in a crate using the taskcluster rust client and base64 was present because both this crate and taskcluster's client use an outdated base64. The update is already on the main branch here but has never been released. Would be nice to get a new version released.

New version should be 4.0.0 because base64 was updated and is technically publicly exposed through the impl here https://github.com/taskcluster/rust-hawk/blob/6652a2311163520585dc66fb173887edde765fcf/src/error.rs#L48 which in turn is exposed through `Error` which is public 
https://github.com/taskcluster/rust-hawk/blob/6652a2311163520585dc66fb173887edde765fcf/src/error.rs#L6
https://github.com/taskcluster/rust-hawk/blob/6652a2311163520585dc66fb173887edde765fcf/src/lib.rs#L159

**Comment by djmitche** [comment]
Hm, maybe a good time to remove that connection..

**Comment by djmitche** [comment]
@lotas / @matt-boris it seems I still _could_ make a release of this crate, but it'd probably be better if someone at Mozilla did.  How would you like to proceed?

**Comment by lotas** [comment]
@djmitche let us try to do it and learn something new ;)

From the https://crates.io/crates/hawk  page it looks like non of us are owners :) @djmitche can you please add us?
I believe it should be possible to add [github team](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner)

**Comment by petemoore** [comment]
@djmitche Do you see any problem with us moving this repo to the mozilla org (so match mozilla/hawk)? Is there anything taskcluster-specific about it?

**Comment by djmitche** [comment]
Moving to the mozilla org makes sense.

**Comment by lotas** [comment]
So we managed to publish new version, and change ownership in between. It is now under github team `taskcluster/core`. 

https://crates.io/crates/hawk

**Comment by jwhitlock** [comment]
> @djmitche Do you see any problem with us moving this repo to the mozilla org (so match mozilla/hawk)? Is there anything taskcluster-specific about it?

Alternatively, we could create a new org for hawk-related repos and move all the hawk stuff there. But, Mozilla has taken over hawk, so it would be more for organization of hawk repos rather than transferring to the community.

**Comment by djmitche** [comment]
My sense is that all the "real" uses of hawk right now are inside Mozilla, although not limited to Taskcluster.  The few non-Mozilla places it got any use seem to have all died.

The repo is only truly critical for the Go client (because Go, ugh), so `mozilla` is probably both most accurate at the current time, and easiest.
