### ISSUE TITLE
Middleware for Rocket

### ISSUE THREAD

**Issue by djmitche** [taskcluster/rust-hawk#7]

**Comment by ckousik** [comment]
Hey @djmitche ! Would this need to be implemented as a `Fairing` for rocket? https://rocket.rs/guide/fairings/

**Comment by djmitche** [comment]
Hi Chinmay!  I don't know much about Rocket, but from looking at that page, it seems so!

**Comment by ckousik** [comment]
My plan was to implement a struct invoking a `rocket::FromRequest`, but it seems that rocket is only usable with rust nightly.

**Comment by djmitche** [comment]
The hyper middleware has moved out to its [own repostitory](https://github.com/taskcluster/hyper-hawk), so it might make sense to do the same with rocket, and make that require nightly.

That said, if rocket is still so early-stages that it requires nightly, then perhaps we would not find any users of such middleware.  I'm not sure how best to find out if that's the case -- perhaps reach out to the Rocket developers?

**Comment by djmitche** [comment]
I'm leaning toward not having any framework-specific middleware.
